"""Unit and regression tests for V1/V2 Brain Regression Harness (Stage 15).

Verifies:
- All 14 V1 decision strings are covered.
- 100% MATCH across all regression scenarios.
- Preservation of target_id and direction vectors.
- Deterministic output across repeated runs.
- Absolute immutability of production q_brain.json and data/q_brain_baseline.json.
- Zero hardware/ADB coupling.
"""

import hashlib
import os
import unittest

from actions.models import ActionType
from tests.brain_regression.runner import run_regression
from tests.brain_regression.scenarios import (
    V1_TO_V2_ACTION_MAP,
    BrainScenario,
    get_all_scenarios,
)


def _file_hash(path: str) -> str:
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


class TestBrainRegressionHarness(unittest.TestCase):
    def setUp(self) -> None:
        self.baseline_path = os.path.join("data", "q_brain_baseline.json")
        self.q_brain_path = "q_brain.json"

        self.initial_baseline_hash = (
            _file_hash(self.baseline_path) if os.path.exists(self.baseline_path) else None
        )
        self.initial_q_brain_hash = (
            _file_hash(self.q_brain_path) if os.path.exists(self.q_brain_path) else None
        )

    def tearDown(self) -> None:
        # Strict guarantee that regression tests NEVER mutate baseline or production files
        if self.initial_baseline_hash and os.path.exists(self.baseline_path):
            self.assertEqual(
                self.initial_baseline_hash,
                _file_hash(self.baseline_path),
                "data/q_brain_baseline.json was modified during regression run!",
            )
        if self.initial_q_brain_hash and os.path.exists(self.q_brain_path):
            self.assertEqual(
                self.initial_q_brain_hash,
                _file_hash(self.q_brain_path),
                "q_brain.json was modified during regression run!",
            )

    def test_all_14_decisions_covered_in_scenarios(self) -> None:
        """Verifies that scenarios cover all 14 inventory decisions without duplicates."""
        scenarios = get_all_scenarios()
        self.assertEqual(len(scenarios), 14, "Must contain exactly 14 scenarios")

        decisions = [s.expected_v1_decision for s in scenarios]
        self.assertEqual(len(set(decisions)), 14, "All 14 decisions must be distinct")

        expected_14 = {
            "TURRET_RETREAT",
            "TACTICAL_RETREAT",
            "KITE_AND_POKE",
            "SWEET_SPOT_BURST",
            "DIVE_ALL_IN",
            "FARM_APPROACH",
            "FARM_KITE_BACK",
            "FARM_SWEET_SPOT",
            "FARM_S1_AOE",
            "LANE_ADVANCE",
            "LANE_PUSH",
            "RIVER_SCOUT",
            "FLANK_ADVANCE",
            "CREEP_INTERCEPT",
        }
        self.assertEqual(set(decisions), expected_14)

    def test_all_scenarios_produce_semantic_match(self) -> None:
        """Executes regression runner and verifies 100% MATCH across all 14 scenarios."""
        scenarios = get_all_scenarios()
        results = run_regression(scenarios)

        self.assertEqual(len(results), 14)
        for r in results:
            self.assertTrue(
                r.match,
                f"Scenario '{r.scenario}' failed: {r.reason}",
            )
            expected_type = V1_TO_V2_ACTION_MAP[r.v1_decision]
            self.assertEqual(r.v2_action, expected_type)

    def test_target_id_preservation_in_regression_actions(self) -> None:
        """Verifies that actions generated by V2 brain in combat and farm maintain target_id."""
        scenarios = get_all_scenarios()
        combat_scenarios = [s for s in scenarios if s.state.enemy_visible]
        farm_scenarios = [s for s in scenarios if s.state.minion_count > 0 and not s.state.enemy_visible]

        self.assertGreater(len(combat_scenarios), 0)
        self.assertGreater(len(farm_scenarios), 0)

        for s in combat_scenarios:
            self.assertIsNotNone(s.state.nearest_enemy_id)
        for s in farm_scenarios:
            self.assertIsNotNone(s.state.nearest_minion_id)

    def test_deterministic_regression_execution(self) -> None:
        """Verifies running the regression twice produces identical results."""
        scenarios = get_all_scenarios()
        run1 = run_regression(scenarios)
        run2 = run_regression(scenarios)

        self.assertEqual(len(run1), len(run2))
        for r1, r2 in zip(run1, run2):
            self.assertEqual(r1.scenario, r2.scenario)
            self.assertEqual(r1.v1_decision, r2.v1_decision)
            self.assertEqual(r1.v2_action, r2.v2_action)
            self.assertEqual(r1.match, r2.match)


if __name__ == "__main__":
    unittest.main()
